version: "3.7"

services:
  UNWINDCSGOAPIMem:
    container_name: UnwindCSGOApiMem
    image: darrenoosthuizen/unwindcsgoapimem:1.0.1
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.UnwindCSGOApiMem.rule=Host(`dev.unwindcsgo.flystudio.co.za`)"
      - "traefik.http.routers.UnwindCSGOApiMem.entrypoints=websecure"
      - "traefik.http.routers.UnwindCSGOApiMem.tls.certresolver=myresolver"
    build:
      context: ./
      dockerfile: ./java.dockerfile
    expose:
      - "8080"
    networks:
      - proxy

networks:
  proxy:
    external: true
